require:
  - rubocop-rails

Layout/EmptyLinesAroundBlockBody:
  Exclude:
   - db/schema.rb
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - db/schema.rb
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 23
Metrics/PerceivedComplexity:
  Max: 10
Rails:
  Enabled: true
Style/StringLiterals:
  Exclude:
   - db/schema.rb
Style/NumericLiterals:
  Exclude:
   - db/schema.rb
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  Exclude:
   - db/*.rb
Style/StderrPuts:
  Exclude:
   - bin/*