default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fur_face_user
  password: FurFace123

development:
  <<: *default
  database: 'fur_face_dev'

test:
  <<: *default
  database: 'fur_face_test'

production:
  <<: *default
  database: 'fur_face_prod'
